### ISSUE TITLE
Get initial data

### ISSUE THREAD

**Issue by MarioKrstevski** [chingu-voyages/geckos-project-20#23]
Make weather info dynamic, by detecting the geolocation for the user and finding info for their location or the nearest you can find. 

You might need to access their geo location and require their approval to share location.

child of #2
depends on #22
![weather info - look.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0a84418e2df000118de4b5/125516c66e82c728ace21e0d46ff919b378a86bbcfe0b145ab1dbdd4254928786b48e13b628ae92dbc56395b4d5a1dac125a5743aaaa8c2ff4e43e708a5b0cee876c0922c22f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e38f8c493c17051c8bfb5527ed.png)

**Comment by jennifersmithuk** [comment]
Had to move everything into Weather component in order to call ComponentDidMount, set state with location and call weather API with location. Think this can be done with async/await calls to a weather-api.js file but will come back and refactor this at a later date.
