### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by MarioKrstevski** [chingu-voyages/geckos-project-20#36]
This task is for making everything pixel perfect, should folow the momentum design, but if you have your creative ideas you can apply them.

child of #8
depends on #35
depends on #34
depends on #33
![quotes - hover.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0a84418e2df000118de4b5/125516c66e82c728ace21e0d46f98195378790e9c2a9b74cb258e2d665043761260ea62864c7b96aea412b025d5749fa125d5b16aefb892ba1b13f268b0a5de9c3714d36976345f3e5db55ea43a82a994e8dbcbd8f48c4eb3a26e1828f4a39191755.png)

**Comment by ir3ne** [comment]
fontawesome twitter icon doesn't work
