### ISSUE TITLE
Image info

### ISSUE THREAD

**Issue by MarioKrstevski** [chingu-voyages/geckos-project-20#60]
Add the information about the image like, whats the name of the image and the name of the  guy who took the shot in the bottom left corner

child of #7
depends on #59
![image info.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0a84418e2df000118de4b5/125516c66e82c728ace21e0d46e1999b2487c3a081efb001e81fe086264c22703d46f9692586b32bed1a2c070c5a4afe135a5f44fbfe8a7da7e06a74984019af80330b2b9b645bf9fa9015ad03ba2a8a4a81b3bc8e4fc3e13824e18f9d02.png)

**Comment by jennifersmithuk** [comment]
Current fetch for Unsplash does not give credit/location info - would need to change to full API https://unsplash.com/documentation
